# Generated by Django 4.2.8 on 2024-05-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polyBizSecd', models.CharField(max_length=15)),
                ('polyBizTy', models.CharField(max_length=30)),
                ('polyBizSjnm', models.CharField(max_length=50)),
                ('polyItcnCn', models.TextField()),
                ('sporCn', models.TextField()),
                ('sporScvl', models.CharField(max_length=100, null=True)),
                ('bizPrdCn', models.CharField(max_length=100, null=True)),
                ('prdRpttSecd', models.CharField(max_length=6)),
                ('rqutPrdCn', models.TextField()),
                ('ageInfo', models.CharField(max_length=100)),
                ('majrRqisCn', models.CharField(max_length=100, null=True)),
                ('empmSttsCn', models.CharField(max_length=100, null=True)),
                ('splzRlmRqisCn', models.CharField(max_length=100, null=True)),
                ('accrRqisCn', models.CharField(max_length=100, null=True)),
                ('prcpCn', models.TextField()),
                ('aditRscn', models.TextField()),
                ('prcpLmttTrgtCn', models.CharField(max_length=300, null=True)),
                ('rqutProcCn', models.TextField()),
                ('pstnPaprCn', models.TextField(null=True)),
                ('jdgnPresCn', models.TextField(null=True)),
                ('rqutUrla', models.CharField(max_length=300, null=True)),
                ('rfcSiteUrla1', models.CharField(max_length=500, null=True)),
                ('rfcSiteUrla2', models.CharField(max_length=500, null=True)),
                ('mngtMson', models.CharField(max_length=100, null=True)),
                ('mngtMrofCherCn', models.CharField(max_length=50, null=True)),
                ('cherCtpcCn', models.CharField(max_length=50, null=True)),
                ('cnsgNmor', models.CharField(max_length=50, null=True)),
                ('tintCherCn', models.CharField(max_length=50, null=True)),
                ('tintCherCtpcCn', models.CharField(max_length=300, null=True)),
                ('etct', models.TextField(null=True)),
                ('polyRlmCd', models.CharField(max_length=6)),
            ],
        ),
    ]
